---
- name: yum groups
  yum: 
    name: 
      - pcre-devel
      - zlib-devel
      - openssl-devel
- name: add group
  group:
    name: nginx
    state: present
- name: add user
  user:
    name: nginx
    groups: nginx
    shell: /sbin/nologin
    remove: yes
    state: present
- name: unarchive
  unarchive:
    src: ./roles/nginx/templates/nginx-1.18.0.tar.gz
    dest: /usr/local/
    mode: '0775'
    remote_src: no
- name: ./configure
  shell: cd /usr/local/nginx-1.18.0/;./configure --prefix=/usr/local/nginx --user=nginx --group=nginx --with-http_dav_module --with-http_stub_status_module --with-http_addition_module --with-http_sub_module --with-http_flv_module --with-http_mp4_module  --with-http_ssl_module --with-http_gzip_static_module;make&& make install  
- name: config file
  copy:
    src: ./roles/nginx/templates/nginx.conf
    dest: /usr/local/nginx/conf/nginx.conf
- name: link
  file:
    src: /usr/local/sbin/
    dest: /usr/local/nginx/sbin/*
    state: link
- name: start nginx
  shell: /usr/local/nginx/sbin/nginx
